public class CustomWrapper {
    private string Id;
    private string Empn;
    private string Gen;
    private string Mob;
    public void setId(string Id){
        this.Id=Id;
    }
    public string getId(){
        return Id;
    }
	public void setEmpn(string Empn){
        this.Empn=Empn;
    }
    public string getEmpn(){
        return Empn;
    }
    public void setGen(string Gen){
        this.Gen=Gen;
    }
    public string getGen(){
        return Gen;
    }
    public void setMob(string Mob){
        this.Mob=Mob;
    }
    public string getMob(){
        return Mob;
    }
}