public class livecoding1301 {
    /*"Create a method which will take 3 parameters, input1, input2, optType.
Use switch case to do arthematic operations based on user input (addition, subtraction, multiplication and division)
Ex: input1 = 2, input2 = 3, optType = add
output: Sum of input1 and input2 is : 5"*/
    public static void task1(integer a, integer b){
        integer c=(a+b);
        system.debug('Sum of 2 numbers:' +c);
    }
    

}