public class PostConnectedClass {
    private string Name;
    private string AccountNumber;
    public void setName(string Name){
        this.Name = Name;
    }
    public string getName(){
        return Name;        
    }
    public void setAccountNumber(string AccountNumber){
        this.AccountNumber = AccountNumber;
    }
    public string getAccountNumber(){
        return AccountNumber;        
    }
}