public class SpoonacularWrapper {
    private integer Id;
    private string name;
    private string image;
    public void setId(integer Id){
        this.Id = Id;
    }
    public integer getId(){
        return Id;
    }
    public void setName(string Name){
        this.Name = Name;
    }
    public string getName(){
        return Name;
    }
    public void setImage(string Image){
        this.Image = Image;
    }
    public string getImage(){
        return Image;        
    }
}